### ISSUE TITLE
关闭应用后，host文件没有还原

### ISSUE THREAD

**Issue by lisonge** [EXACG/pandownload-fake-localserver#1]
尊敬的开发者，你好，我有一些问题
win10x64使用软件后host文件内容如下
```
127.0.0.1 pandownload.com
```
1.为啥我之前的解析地址没得了？
2.请问host文件读写是用的w覆盖写入模式吗？
3.使用注释#127.0.0.1 pandownload.com之后再打开该软件，host文件又为什么不更改了？

**Comment by EXACG** [comment]
1.原本hosts文件的话 会备份到hosts.1 文件
2.是用覆盖写入的
3.检测词条是不检测注释的 即使你注释了也会被视为写入过

**Comment by EXACG** [comment]
> 对于第三点 我会做些修正的

最新版本,会在软件正常关闭时,恢复你默认的hosts文件
