### ISSUE TITLE
关闭软件后。我的host直接空了

### ISSUE THREAD

**Issue by rick-lzr** [EXACG/pandownload-fake-localserver#2]
我觉得可能是我个人原因。。因为我是打开host然后又打开软件了。所以issue一下。因为我host里面有很多DNS，那一次直接全都gg了。QAQ现在还没找回来。

**Comment by EXACG** [comment]
开启软件:原先hosts 重命名为 hosts.1 并且写入单行的hosts
关闭软件:将hosts.1 复制一份为 hosts文件(保留hosts.1作为备份)
